"""Configure general scaffolding."""
from sphinx.config import Config


def configure_general_scaffolding(config: Config) -> None:
    """Configures general scaffolding."""

    # Add any paths that contain templates here, relative to this directory.
    config.templates_path = ["_templates"]

    # The language for content autogenerated by Sphinx. Refer to documentation
    # for a list of supported languages.
    #
    # This is also used if you do content translation via gettext catalogs.
    # Usually you set "language" from the command line for these cases.
    config.language = "en"

    # List of patterns, relative to source directory, that match files and
    # directories to ignore when looking for source files.
    # This pattern also affects html_static_path and html_extra_path.
    config.exclude_patterns = [
        "_build",
        "Thumbs.db",
        ".DS_Store",
        "**/build",
        "**/docs",
    ]
